[project]
name = "govbr-auth"
version = "0.2.2"
description = "Biblioteca assíncrona de autenticação com o Gov.br para FastAPI."
authors = [
    { name="Joab Leite", email="leitejoab@gmail.com" }
]
readme = "README.md"
license = "MIT"
keywords = ["gov.br", "autenticação", "fastapi", "oauth2", "openid-connect"]
requires-python = ">=3.11"

dependencies = [
    "httpx",
    "PyJWT>=2.13,<3",
    "cryptography",
    "python-dotenv",
    "pydantic>=2,<3",
    "fastapi"
]

[project.optional-dependencies]
fake = ["python-multipart"]
dev = ["uvicorn", "pytest", "pytest-asyncio", "pytest-mock", "black", "build", "flake8", "pytest-cov"]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["govbr_auth*"]
exclude = ["govbr_auth.__pycache__*", "govbr_auth.*.__pycache__*"]

[project.urls]
Homepage = "https://github.com/cereja-project/govbr_auth"
Repository = "https://github.com/cereja-project/govbr_auth"
Documentation = "https://govbr-auth.readthedocs.io/"
Issues = "https://github.com/cereja-project/govbr_auth/issues"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
